cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns=[

    path('',views.cart_detail,name='cart_detail'),
    path('order_succcess',views.order_success,name='order_success'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

kshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('password_reset/',auth_view.PasswordResetView.as_view(template_name='authenticate/password_reset_form.html'),name='password_reset'),
    path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='authenticate/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(template_name='authenticate/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='authenticate/password_reset_complete.html'),name='password_reset_complete'),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name='shop'

urlpatterns=[
    path('sign_up/',views.sign_up,name='sign_up'),
    path('login_user/',views.login_user,name='login_user'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('profile_edit/',views.profile_edit,name='profile_edit'),
    path('<str:category_slug>/',views.product_list,name='product_list_category'),
    path('<int:id>/<str:slug>/',views.product_detail,name='product_detail'), #한글일때는 <str:slug>방식을 쓴다.
    path('',views.product_list,name='product_list'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

ITEM_QUANTITY=[(i,str(i)) for i in range(1,11)]

class CartCountForm(forms.Form):
    quantity=forms.TypedChoiceField(choices=ITEM_QUANTITY,coerce=int)

cart/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .cart import Cart
from shop.models import Product,User,Order
from .forms import CartCountForm



@require_POST
def cart_add(request,product_id):
    if request.user.is_authenticated:
        userid=request.user.id
    else:
        return redirect('shop:login_user')
    cart=Cart(request,userid)
    product=get_object_or_404(Product,id=product_id)
    form=CartCountForm(request.POST)
    if form.is_valid():
        quantity=form.cleaned_data['quantity']
        cart.add(product,quantity)

    return redirect('cart:cart_detail')

def cart_detail(request):
    cart=Cart(request,request.user.id)
    obj = User.objects.get(id=request.user.id)
    if request.method=="POST":
        order=Order()
        order.user=request.user
        order.name = request.POST["name"]
        order.phone = request.POST["phone"]
        order.address = request.POST["address"]
        order.email = request.POST["email"]
        order.orderitem=cart.for_ordered_item()
        order.save()
        messages.success(request,"주문 성공 하였습니다!!!")
        cart.clear()
        return redirect('cart:order_success')
    else:
        return render(request,'cart/detail.html',{'cart':cart,'obj':obj})

def cart_remove(request,product_id):
    cart=Cart(request,request.user.id)
    product=get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def order_success(request):
    order=Order.objects.filter(user_id=request.user.id).order_by('-created_at')

    return render(request,'cart/ordered.html',{'order':order})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}


{% block content %}




<div class="h-100 d-flex align-items-center justify-content-center">
  <p>
    <h1>Shopping cart</h1>
  </p>
  {% if messages %}
    {% for message in messages %}
  <div class="alert alert-primary" role="alert">
    <h3><strong> {{ message }} </strong></h3>
  </div>
    {% endfor %}
  {% endif %}
</div>
<div class="h-100 d-flex align-items-center justify-content-center">
<table  >
  <thead>
  <tr>
    <th>Image</th>
    <th>Product</th>
    <th>Quantity</th>
    <th>Remove</th>
    <th>Unit Price</th>
    <th>Price</th>
  </tr>
  </thead>
  <tbody>
  {% for item in cart %}
  {% with product=item.product %}
  <tr>
    <td>
      <a href="{{ product.get_absolute_url }}">
        <img src="{% if product.image %}{{ product.image.url }}
                  {% else %}{% static 'img/no_image.png' %}{% endif %}" width="200" height="200">
      </a>
    </td>
    <td>{{ product.name }} </td>
    <td>{{ item.quantity }}</td>
    <td>
      <form action="{% url 'cart:cart_remove' product.id %}" method="post">
        {% csrf_token %}
      <input type="submit" value="Remove">
      </form>
    </td>
    <td class="num">{{ item.price }}&nbsp(원)</td>
    <td class="num">{{ item.total_price }}&nbsp(원)</td>
  </tr>
  {% endwith %}
  {% endfor %}
  <tr class="total">
    <td><h3>Total</h3></td>
    <td colspan="4"></td>
    <td class="num"><h3>{{ cart.get_total_price }}&nbsp(원)</h3></td>
  </tr>
  </tbody>
</table>

  </div>
<br><br><br>

<div class="h-100 d-flex align-items-center justify-content-center">

    <form action="" method="post">
      {% csrf_token %}
      받는 분: <input type="text" name="name" id="name"> <br>
      이메일: <input type="email" name="email" id="email" ><br>
      배송지 주소: <input type="text" name="address" id="address" size="40" ><br> <!-- input 태그 크기는 글자수인 size 속성으로 -->
      휴대전화: <input type="text" name="phone" id="phone" ><br>
      <input type="submit" value="계산">
      <a href="{% url 'shop:product_list' %}" class="buttonlight">쇼핑 계속</a>
    </form>
</div>


<script>
window.onload=function(){
    document.getElementById("name").value="{{ obj.name }}";
    document.getElementById("email").value="{{ obj.email }}";
    document.getElementById("address").value="{{ obj.address }}";
    document.getElementById("phone").value="{{ obj.phone }}";
}
</script>

{% endblock %}

cart/templates/cart/ordered.html
{% extends "shop/base.html" %}
{% load static %}


{% block content %}


<div class="h-100 d-flex align-items-center justify-content-center">
    <h1>주문 내역</h1>
  {% if messages %}
    {% for message in messages %}
  <div class="alert alert-primary" role="alert">
    <h3><strong> {{ message }} </strong></h3>
  </div>
    {% endfor %}
  {% endif %}
</div>
<br><br>

<div class="h-100 d-flex align-items-center justify-content-center">
    {% for i in order %}
    주문일 : {{ i.created_at }}<br>
      받는 분: {{ i.name }} <br>
      이메일: {{ i.email }}<br>
      배송지 주소: {{ i.address }}<br>
      휴대전화: {{ i.phone }}<br>
</div>



{% for j in i.orderitem.values %} <!-- jsonfield 로서 i.orderitem.items ,i.orderitem.i.keys, i.orderitem.values 가능 -->
<div class="h-100 d-flex align-items-center justify-content-center">
    <img src="{{ j.product_image }}" width="200" height="200"> &nbsp&nbsp
    {{ j.product_name }} &nbsp&nbsp
    {{ j.price }} &nbsp&nbsp
    {{ j.quantity }} &nbsp&nbsp
    {{ j.prodcut_category }} &nbsp&nbsp
    {{ j.total_price }}<br><br>
    
    </div>
{% endfor %}


{% endfor %}
{% endblock %}