cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns=[

    path('',views.cart_detail,name='cart_detail'),
    path('order_succcess',views.order_success,name='order_success'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

kshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('password_reset/',auth_view.PasswordResetView.as_view(template_name='authenticate/password_reset_form.html'),name='password_reset'),
    path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='authenticate/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(template_name='authenticate/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='authenticate/password_reset_complete.html'),name='password_reset_complete'),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name='shop'

urlpatterns=[
    path('sign_up/',views.sign_up,name='sign_up'),
    path('login_user/',views.login_user,name='login_user'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('profile_edit/',views.profile_edit,name='profile_edit'),
    path('<str:category_slug>/',views.product_list,name='product_list_category'),
    path('<int:id>/<str:slug>/',views.product_detail,name='product_detail'), #한글일때는 <str:slug>방식을 쓴다.
    path('',views.product_list,name='product_list'),

]

shop/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.urls import reverse


class CustomUserManager(UserManager):
    def _create_user(self,email,password,**extra_fields):
        if not email:
            raise ValueError("이메일은 필수 입니다.")

        email=self.normalize_email(email)
        user=self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):   #실제 User 테이블의 field들
    email=models.EmailField(blank=True,default='',unique=True)
    name=models.CharField(max_length=200,blank=True,default='')
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=20)

    is_active=models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined=models.DateTimeField(default=timezone.now) #기본값이며 생성 시 선택, 편집 가능하다. auto_now_add 랑 조금 다르다
    last_login=models.DateTimeField(blank=True,null=True)

    objects=CustomUserManager()   #모든 개체 필드들을 CustomUserManager를 거쳐서 가져온다.

    USERNAME_FIELD='email'   #manage.py createsuperuser 시 name을 email로 대체
    EMAIL_FIELD='email'     #manage.py cratesuperuser 시 이메일
    REQUIRED_FIELDS = []  # 그외 꼭 넣고 싶은 필드들

    class Meta:
        verbose_name='User'          # 모델 이름을 verbose_name에 모델의 복수명을 verbose_name_plural에 적는다.
        verbose_name_plural='Users'  #왼쪽 Users 를 누르면 등록한 유저들의 리스트가 나오는데 또한, 그 필드 이름이 User인 걸 볼 수 있다.

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name or self.email.split('@')[0]  #name 필드에 이름 값을 채우기 전까지는 admin 관리창 우측 상단에 메일의 아이디만 나올 것이다.


class Category(models.Model):
    name=models.CharField(max_length=50,db_index=True,unique=True)
    slug = models.SlugField(max_length=50, unique=True,allow_unicode=True)  # 데이타로 url(주소)만드는 방식을 지원함, unicode...는 한글도 가능하게

    class Meta:
        ordering = ('name',)  # ordering은 반드시 튜플로 즉, 쉼표 잊지 말길, 내림차순은 ('-name',)
        verbose_name = 'category'
        #db_table = 'category'  실제 mysql에서 디폴트로 생성되는<app_name>_테이블명을 원하는 테이블명으로 바꿔주는 역할을 한다.
    def __str__(self):
        return self.name

    def get_absolute_url(self):  # 주로 list에서 해당 아이템(인스턴스)의 detail 정보를 얻는데 사용된다.
        return reverse('shop:product_list_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=50, unique=True,db_index=True)
    slug = models.SlugField(max_length=50, db_index=True,allow_unicode=True)
    image=models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description=models.TextField(blank=True)
    price=models.IntegerField() #decimal_places은 필수로 소수점 설정
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)

    class Meta:
        ordering=('name',)
        models.Index(fields=['id', 'slug'])  #id 단독 검색 혹은 id와 slug를 동시 검색하는데 유리하다. 하지만 slug를 단독 검색하는데는 불리

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id,self.slug])


class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=100, null=False)
    email=models.CharField(max_length=100, null=False)
    phone = models.CharField(max_length=100, null=False)
    address = models.CharField(max_length=100, null=False)
    orderitem=models.JSONField()
    orderstatus=(
        ('pending','pending'),
        ('out for shipping','out for shipping'),
        ('completed','completed'),
    )
    #CharField에 choices 옵션을 이용하여 콤보를 만들고 2차원 튜플로 구성하되, 앞에 값이 DB저장 2번째 값은 템플릿에 보여질 값
    status=models.CharField(max_length=150,choices=orderstatus,default='pending')
    message=models.TextField(null=True)
    tracking_no=models.CharField(max_length=50,null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


    def __str__(self):
        return '{} - {}'.format(self.id, self.tracking_no)

shop/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, User
from cart.forms import CartCountForm

from cart.cart import Cart


def product_list(request, category_slug=None):
    category=None
    categories=Category.objects.all()
    products=Product.objects.filter(available=True)
    if category_slug:
        category=get_object_or_404(Category,slug=category_slug)
        products=products.filter(category=category)
    context={
        'category':category,
        'categories':categories,
        'products':products
    }
    return render(request,'shop/product_list.html',context)


def product_detail(request,id,slug):
    product=get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_add_form=CartCountForm()
    context={
        'product':product,
        'form':cart_add_form
    }
    return render(request,'shop/product_detail.html',context)


def login_user(request):
    if request.method=="POST":
        email=request.POST["email"]
        password=request.POST["password"]
        print("email: ",email,"   password: ",password)
        user=authenticate(request,email=email,password=password)
        if user is not None:
            login(request,user)
            return redirect('shop:product_list')
        else:
            messages.success(request,"없는 사람입니다. 다시 로그인 하세욥!")
            return redirect('shop:login_user')
    else:
        return render(request,'authenticate/login.html',{})



def logout_user(request):
    logout(request)
    return redirect('shop:product_list')


def sign_up(request):
    if request.method=="POST":
        user=User()
        user.name=request.POST["name"]
        user.email=request.POST["email"]
        user.phone=request.POST["phone"]
        temp=request.POST["address1"]+ " " +request.POST["address2"]
        user.address=temp
        user.password=request.POST["password"]
        user.set_password(user.password)
        user.save()
        return redirect('shop:login_user')
    else:
        return render(request,'authenticate/sign_up.html',{})

def profile_edit(request):
    user=User.objects.get(id=request.user.id)
    if request.method=="POST":
        name=request.POST["name"]
        phone=request.POST["phone"]
        email=request.POST["email"]
        User.objects.filter(id=request.user.id).update(name=name,phone=phone,email=email)
        messages.success(request,"정보를 수정하였습니다")
        return redirect('shop:profile_edit')
    else:
        context={
            'name':user.name,
            'phone':user.phone,
            'email':user.email
        }
        return render(request,'authenticate/profile_edit.html',context)

shop/templates/authenticate/login.html
{% extends "shop/base.html" %}
{% load static %}


{% block content %}
<div>
	<h2>로그인</h2>
	</div>

<div>
  {% if messages %}
    {% for message in messages %}
  <div class="alert alert-primary" role="alert">
    <h3><strong> {{ message }} </strong></h3>
  </div>
    {% endfor %}
  {% endif %}
</div>

	<form action="" method="POST" id="frm">
		 {% csrf_token %}
	<div class="login">
	<table cellspacing="2" align="center" cellpadding="8" border="0">
	<tr>
	<td align="right">이메일 :</td>
	<td><input type="text" placeholder="Enter Email ID here" id="email" name="email" class="tb" /></td>
	</tr>   <!-- id는 javascript에서 사용하기 위한 식별자이고, name은 input 태그의 값을 넘기기 위해서 쓴다.  -->
	<tr>
	</tr>
	<tr>
	<td align="right">비밀번호 :</td>
	<td><input type="password" placeholder="Enter Password here" id="password" name="password" class="tb" /></td>
	</tr>
	<tr>
	<td></td>
	<td>
	<input type="button" value="로그인" class="btn" onclick="go_login()"/></td>
	<td><a href="{% url 'password_reset' %}">비밀번호찾기</a></td>
		<td><a href="{% url 'shop:sign_up' %}">회원가입</a></td>
	</tr>
	</table>
	</div>
		</form>


<script>
     function go_login()
	{

		var email= document.getElementById("email").value;
		var password= document.getElementById("password").value;

		var pwd_expression = /(?=.*\d)(?=.*[a-zA-Z]).{8,15}/;
		var name_ex = /[A-Za-z]+$/;
		var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;


		if(email=='')
		{
			alert('이메일을 입력하세요');
		}
		else if (!filter.test(email))
		{
			alert('잘못된 이메일 형식입니다.');
		}

		else if(password=='')
		{
			alert('비밀번호를 입력하세요');
		}

		else if(!pwd_expression.test(password))
		{
			alert ('대문자 소문자 숫자 영어 특수기호를 혼합하세요');
		}

		else if(document.getElementById("password").value.length < 8)
		{
			alert ('비밀번호는 최소 8자 이상요');
		}
		else if(document.getElementById("password").value.length > 12)
		{
			alert ('비밀번호는 최대 12자 이하요');
		}
		else{
		document.getElementById("frm").submit()
		}
	}
</script>

{% endblock %}

shop/templates/authenticate/password_reset_complete.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<h3>비밀번호가 변경 되었습니다.</h3>
<p>
    비밀변호가 변경되었으니, 로그인 하세요
</p>
{% endblock %}

shop/templates/authenticate/password_reset_confirm.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<h3>비밀번호 잊었음</h3>
{% if validlink %}
<h3>비밀번호 변경 하세요</h3>
<form method="post">
    {% csrf_token %}
    {{ form.new_password1 }}
    {{ form.new_password2 }}
    <button type="submit">change password</button>
</form>
{% else %}
<p>
    이미 변경 되었습니다.
    다시 변경하고자 한다면, 다시 처음으로 돌아가세요
</p>
{% endif %}
{% endblock %}

shop/templates/authenticate/password_reset_done.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<h3>메일 확인 하시길 바랍니다</h3>
<p>확인 메일을 전송 하였습니다.</p>
<p>스팸 메일함도 확인 하세요</p>
{% endblock %}

shop/templates/authenticate/password_reset_form.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<h3>비밀번호 잊었음</h3>
<form method="post">
    {% csrf_token %}
    {{ form.email }}
    <button type="submit">보내기</button>
</form>
{% endblock %}

shop/templates/authenticate/profile_edit.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
<div>
	<h2>회원 정보</h2>
	</div>

<div>
  {% if messages %}
    {% for message in messages %}
  <div class="alert alert-primary" role="alert">
    <h3><strong> {{ message }} </strong></h3>
  </div>
    {% endfor %}
  {% endif %}
</div>

	<form action="" method="POST" id="frm">
		 {% csrf_token %}
	<div class="login">
	<table cellspacing="2" align="center" cellpadding="8" border="0">
	<tr>
	<td align="right">별명 :</td>
	<td><input type="text" placeholder="{{ name }}" id="name" name="name" class="tb" /></td>
	</tr>
	<tr>
	<td align="right">이메일 :</td>
	<td><input type="text" placeholder="{{ email }}" id="email" name="email" class="tb" /></td>
	</tr>
	<tr>
	</tr>

	<tr>
	<td align="right"></td>
		<td><input type="text" id="postcode" placeholder="우편번호" class="tb"></td>
	</tr>
		<tr>
			<td align="right">주소:</td>
			<td><input type="text"  id="address"  name="address1" class="tb"/></td>
			<td><input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기" class="tb"></td>
		</tr>
		<tr>
		<td align="right">상세 주소 :</td>
	<td><input type="text"  id="address2" name="address2" class="tb" /></td>
	</tr>
		<tr>
			<td align="right"></td><td><input type="text" id="address3" placeholder="참고항목" class="tb"></td>
	</tr>
	<tr>
	</tr>
	<tr>
	<td align="right">전화번호 :</td>
	<td ><input type="text"  id="phone" placeholder="{{ phone }}" name="phone" class="tb" /></td>
	</tr>
	<tr>
	</tr>
	<tr>
	<td></td>
	<td>
    <input type="button" value="확인" class="btn" onclick="registration()" />
	<input type="button" value="취소" onclick="cancelFunc()" id="res" class="btn" />
	</td>
	</tr>
	</table>
	</div>
	</form>
	<!-- create account box ending here.. -->
	<!-- Main div ending here... -->

<script>

     function registration()
	{

		var name= document.getElementById("name").value;
		var phone= document.getElementById("phone").value;
		var email= document.getElementById("email").value;

		var password_expression = /(?=.*\d)(?=.*[a-zA-Z]).{8,15}/;
		var name_ex = /^[A-Za-z]+/;
		var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+/;
		var etc=/^[가-힣\s\d\-]+/;

		if(name=='')
		{
			alert('이름을 입력하세요');
		}
		else if(!name_ex.test(name))
		{
			alert('이름은 알파벳으로 1자 이상');
		}
		else if(email=='')
		{
			alert('이메일을 입력하세요');
		}
		else if (!filter.test(email))
		{
			alert('잘못된 이메일 형식입니다.');
		}
		else if(address=='')
		{
			alert('주소를 입력하세요');
		}
		//else if (!etc.test(address))
		//{
		//	alert('잘못된 주소 형식입니다.');
		//}
		else if(address2=='')
		{
			alert('주소를 입력하세요');
		}
		//else if (!etc.test(address2))
		//{
		//	alert('잘못된 주소 형식입니다.');
		//}
		else if(phone=='')
		{
			alert('이메일을 입력하세요');
		}
		else if (!etc.test(phone))
		{
			alert('잘못된 전화번호 형식입니다.');
		}
		else
		{
			   document.getElementById("frm").submit();
		}
	}

	function cancelFunc(){
	window.location="{% url 'shop:product_list' %}";
	}
</script>


<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
    function sample6_execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var addr = ''; // 주소 변수
                var extraAddr = ''; // 참고항목 변수

                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    addr = data.roadAddress;
                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    addr = data.jibunAddress;
                }

                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                if(data.userSelectedType === 'R'){
                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                    // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있고, 공동주택일 경우 추가한다.
                    if(data.buildingName !== '' && data.apartment === 'Y'){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                    if(extraAddr !== ''){
                        extraAddr = ' (' + extraAddr + ')';
                    }
                    // 조합된 참고항목을 해당 필드에 넣는다.
                    document.getElementById("address3").value = extraAddr;

                } else {
                    document.getElementById("address3").value = '';
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('postcode').value = data.zonecode;
                document.getElementById("address").value = addr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById("address2").focus();
            }
        }).open();
    }
</script>
{% endblock %}

shop/templates/authenticate/sign_up.html
{% extends "shop/base.html" %}
{% load static %}


{% block content %}
<div>
	<h2>회원 가입</h2>
	</div>

<div>
  {% if messages %}
    {% for message in messages %}
  <div class="alert alert-primary" role="alert">
    <h3><strong> {{ message }} </strong></h3>
  </div>
    {% endfor %}
  {% endif %}
</div>

	<form action="" method="POST" id="frm">
		 {% csrf_token %}
	<div class="login">
	<table cellspacing="2" align="center" cellpadding="8" border="0">
	<tr>
	<td align="right">별명 :</td>
	<td><input type="text" placeholder="Enter user here" id="name" name="name" class="tb" /></td>
	</tr>
	<tr>
	<td align="right">이메일 :</td>
	<td><input type="text" placeholder="Enter Email ID here" id="email" name="email" class="tb" /></td>
	</tr>
	<tr>
	</tr>
	<tr>
	<td align="right">비밀번호 :</td>
	<td><input type="password"  id="password" name="password" class="tb" /></td>
	</tr>
	<tr>
	<td align="right">비밀번호 재입력 :</td>
	<td><input type="password"  id="password2" class="tb" /></td>
	</tr>
	<tr>
	<td align="right"></td>
		<td><input type="text" id="postcode" placeholder="우편번호" class="tb"></td>
	</tr>
		<tr>
			<td align="right">주소:</td>
			<td><input type="text"  id="address"  name="address1" class="tb"/></td>
			<td><input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기" class="tb"></td>
		</tr>
		<tr>
		<td align="right">상세 주소 :</td>
	<td><input type="text"  id="address2" name="address2" class="tb" /></td>
	</tr>
		<tr>
			<td align="right"></td><td><input type="text" id="address3" placeholder="참고항목" class="tb"></td>
	</tr>
	<tr>
	</tr>
	<tr>
	<td align="right">전화번호 :</td>
	<td ><input type="text"  id="phone" name="phone" class="tb" /></td>
	</tr>
	<tr>
	</tr>
	<tr>
	<td></td>
	<td>
        <input type="button" value="확인" class="btn" onclick="registration()" />
	<input type="reset" value="초기화" onclick="clearFunc()" id="res" class="btn" />
	</td>
	</tr>
	</table>
	</div>
	</form>
	<!-- create account box ending here.. -->
	<!-- Main div ending here... -->

<script>

     function registration()
	{

		var name= document.getElementById("name").value;
		var address= document.getElementById("address").value;
		var phone= document.getElementById("phone").value;
		var email= document.getElementById("email").value;
		var password= document.getElementById("password").value;
		var password2= document.getElementById("password2").value;

		var password_expression = /(?=.*\d)(?=.*[a-zA-Z]).{8,15}/;
		var name_ex = /^[A-Za-z]+$/;
		var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
		var etc=/^[가-힣\s\d\-]+$/;

		if(name=='')
		{
			alert('이름을 입력하세요');
		}
		else if(!name_ex.test(name))
		{
			alert('이름은 알파벳으로 1자 이상');
		}
		else if(email=='')
		{
			alert('이메일을 입력하세요');
		}
		else if (!filter.test(email))
		{
			alert('잘못된 이메일 형식입니다.');
		}
		else if(address=='')
		{
			alert('주소를 입력하세요');
		}
		//else if (!etc.test(address))
		//{
		//	alert('잘못된 주소 형식입니다.');
		//}
		else if(address2=='')
		{
			alert('주소를 입력하세요');
		}
		//else if (!etc.test(address2))
		//{
		//	alert('잘못된 주소 형식입니다.');
		//}
		else if(phone=='')
		{
			alert('이메일을 입력하세요');
		}
		else if (!etc.test(phone))
		{
			alert('잘못된 전화번호 형식입니다.');
		}

		else if(password=='')
		{
			alert('비밀번호를 입력하세요');
		}
		else if(password2=='')
		{
			alert('비밀번호를 한 번 더 입력하세요');
		}
		else if(!password_expression.test(password))
		{
			alert ('대문자 소문자 숫자 영어 특수기호를 혼합하세요');
		}
		else if(password != password2)
		{
			alert ('비밀번호와 재비밀번호가 다릅니다.');
		}
		else if(document.getElementById("password").value.length < 8)
		{
			alert ('비밀번호는 최소 8자 이상요');
		}
		else if(document.getElementById("password").value.length > 12)
		{
			alert ('비밀번호는 최대 12자 이하요');
		}
		else
		{
               alert('가입을 축하드립니다. 로그인으로 이동합니다.');
			   document.getElementById("frm").submit();
		}
	}
	function clearFunc()
	{
		document.getElementById("name").value="";
		document.getElementById("email").value="";
		document.getElementById("password").value="";
		document.getElementById("password2").value="";
	}

</script>


<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
    function sample6_execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var addr = ''; // 주소 변수
                var extraAddr = ''; // 참고항목 변수

                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    addr = data.roadAddress;
                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    addr = data.jibunAddress;
                }

                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                if(data.userSelectedType === 'R'){
                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                    // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있고, 공동주택일 경우 추가한다.
                    if(data.buildingName !== '' && data.apartment === 'Y'){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                    if(extraAddr !== ''){
                        extraAddr = ' (' + extraAddr + ')';
                    }
                    // 조합된 참고항목을 해당 필드에 넣는다.
                    document.getElementById("address3").value = extraAddr;

                } else {
                    document.getElementById("address3").value = '';
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('postcode').value = data.zonecode;
                document.getElementById("address").value = addr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById("address2").focus();
            }
        }).open();
    }
</script>
{% endblock %}