cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns=[

    path('',views.cart_detail,name='cart_detail'),
    path('order_succcess',views.order_success,name='order_success'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

kshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('password_reset/',auth_view.PasswordResetView.as_view(template_name='authenticate/password_reset_form.html'),name='password_reset'),
    path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='authenticate/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(template_name='authenticate/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='authenticate/password_reset_complete.html'),name='password_reset_complete'),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name='shop'

urlpatterns=[
    path('sign_up/',views.sign_up,name='sign_up'),
    path('login_user/',views.login_user,name='login_user'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('profile_edit/',views.profile_edit,name='profile_edit'),
    path('<str:category_slug>/',views.product_list,name='product_list_category'),
    path('<int:id>/<str:slug>/',views.product_detail,name='product_detail'), #한글일때는 <str:slug>방식을 쓴다.
    path('',views.product_list,name='product_list'),

]

shop/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.urls import reverse


class CustomUserManager(UserManager):
    def _create_user(self,email,password,**extra_fields):
        if not email:
            raise ValueError("이메일은 필수 입니다.")

        email=self.normalize_email(email)
        user=self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):   #실제 User 테이블의 field들
    email=models.EmailField(blank=True,default='',unique=True)
    name=models.CharField(max_length=200,blank=True,default='')
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=20)

    is_active=models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined=models.DateTimeField(default=timezone.now) #기본값이며 생성 시 선택, 편집 가능하다. auto_now_add 랑 조금 다르다
    last_login=models.DateTimeField(blank=True,null=True)

    objects=CustomUserManager()   #모든 개체 필드들을 CustomUserManager를 거쳐서 가져온다.

    USERNAME_FIELD='email'   #manage.py createsuperuser 시 name을 email로 대체
    EMAIL_FIELD='email'     #manage.py cratesuperuser 시 이메일
    REQUIRED_FIELDS = []  # 그외 꼭 넣고 싶은 필드들

    class Meta:
        verbose_name='User'          # 모델 이름을 verbose_name에 모델의 복수명을 verbose_name_plural에 적는다.
        verbose_name_plural='Users'  #왼쪽 Users 를 누르면 등록한 유저들의 리스트가 나오는데 또한, 그 필드 이름이 User인 걸 볼 수 있다.

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name or self.email.split('@')[0]  #name 필드에 이름 값을 채우기 전까지는 admin 관리창 우측 상단에 메일의 아이디만 나올 것이다.


class Category(models.Model):
    name=models.CharField(max_length=50,db_index=True,unique=True)
    slug = models.SlugField(max_length=50, unique=True,allow_unicode=True)  # 데이타로 url(주소)만드는 방식을 지원함, unicode...는 한글도 가능하게

    class Meta:
        ordering = ('name',)  # ordering은 반드시 튜플로 즉, 쉼표 잊지 말길, 내림차순은 ('-name',)
        verbose_name = 'category'
        #db_table = 'category'  실제 mysql에서 디폴트로 생성되는<app_name>_테이블명을 원하는 테이블명으로 바꿔주는 역할을 한다.
    def __str__(self):
        return self.name

    def get_absolute_url(self):  # 주로 list에서 해당 아이템(인스턴스)의 detail 정보를 얻는데 사용된다.
        return reverse('shop:product_list_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=50, unique=True,db_index=True)
    slug = models.SlugField(max_length=50, db_index=True,allow_unicode=True)
    image=models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description=models.TextField(blank=True)
    price=models.IntegerField() #decimal_places은 필수로 소수점 설정
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)

    class Meta:
        ordering=('name',)
        models.Index(fields=['id', 'slug'])  #id 단독 검색 혹은 id와 slug를 동시 검색하는데 유리하다. 하지만 slug를 단독 검색하는데는 불리

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id,self.slug])


class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=100, null=False)
    email=models.CharField(max_length=100, null=False)
    phone = models.CharField(max_length=100, null=False)
    address = models.CharField(max_length=100, null=False)
    orderitem=models.JSONField()
    orderstatus=(
        ('pending','pending'),
        ('out for shipping','out for shipping'),
        ('completed','completed'),
    )
    #CharField에 choices 옵션을 이용하여 콤보를 만들고 2차원 튜플로 구성하되, 앞에 값이 DB저장 2번째 값은 템플릿에 보여질 값
    status=models.CharField(max_length=150,choices=orderstatus,default='pending')
    message=models.TextField(null=True)
    tracking_no=models.CharField(max_length=50,null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


    def __str__(self):
        return '{} - {}'.format(self.id, self.tracking_no)

shop/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, User
from cart.forms import CartCountForm

from cart.cart import Cart


def product_list(request, category_slug=None):
    category=None
    categories=Category.objects.all()
    products=Product.objects.filter(available=True)
    if category_slug:
        category=get_object_or_404(Category,slug=category_slug)
        products=products.filter(category=category)
    context={
        'category':category,
        'categories':categories,
        'products':products
    }
    return render(request,'shop/product_list.html',context)


def product_detail(request,id,slug):
    product=get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_add_form=CartCountForm()
    context={
        'product':product,
        'form':cart_add_form
    }
    return render(request,'shop/product_detail.html',context)


def login_user(request):
    if request.method=="POST":
        email=request.POST["email"]
        password=request.POST["password"]
        print("email: ",email,"   password: ",password)
        user=authenticate(request,email=email,password=password)
        if user is not None:
            login(request,user)
            return redirect('shop:product_list')
        else:
            messages.success(request,"없는 사람입니다. 다시 로그인 하세욥!")
            return redirect('shop:login_user')
    else:
        return render(request,'authenticate/login.html',{})



def logout_user(request):
    logout(request)
    return redirect('shop:product_list')


def sign_up(request):
    if request.method=="POST":
        user=User()
        user.name=request.POST["name"]
        user.email=request.POST["email"]
        user.phone=request.POST["phone"]
        temp=request.POST["address1"]+ " " +request.POST["address2"]
        user.address=temp
        user.password=request.POST["password"]
        user.set_password(user.password)
        user.save()
        return redirect('shop:login_user')
    else:
        return render(request,'authenticate/sign_up.html',{})

def profile_edit(request):
    user=User.objects.get(id=request.user.id)
    if request.method=="POST":
        name=request.POST["name"]
        phone=request.POST["phone"]
        email=request.POST["email"]
        User.objects.filter(id=request.user.id).update(name=name,phone=phone,email=email)
        messages.success(request,"정보를 수정하였습니다")
        return redirect('shop:profile_edit')
    else:
        context={
            'name':user.name,
            'phone':user.phone,
            'email':user.email
        }
        return render(request,'authenticate/profile_edit.html',context)

shop/templates/shop/base.html
<!doctype html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Album example · Bootstrap v5.0</title>

    <!-- Bootstrap core CSS -->
<title>{% block mytitle%}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        </ul>

        <form class="d-flex">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">search</button>
      </form>


        <ul class="d-flex">
       {% if user.is_authenticated %}
          <li><a class="dropdown-item" href="{% url 'shop:logout_user' %}" ><img src="{% static 'img/logout.png' %}" width="50" height="50"></a></li>
          <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle "  data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" style="color:#FFA500">{{ user.name }}</a>
    <ul class="dropdown-menu bg-dark" >
      <li><a class="dropdown-item" href="{% url 'shop:profile_edit' %}" style="color:#FFA500">정보수정</a></li>
      <li><a class="dropdown-item" href="{% url 'cart:order_success'%}" style="color:#FFA500">주문목록</a></li>
      <li><a class="dropdown-item" href="#" style="color:#FFA500">빈공란</a></li>
      <li><hr class="dropdown-divider" style="color:#FFA500"></li>
    </ul>
    </li>
      {% else %}
            <li class="nav-item">
                <a href="{% url 'shop:login_user' %}" class="nav-link" style="color:#FFA500"><img src="{% static 'img/login.png' %}" width="50" height="50"></a>
            </li>
            {% endif %}
            </ul>

        <span class="p-2">
        <ul>
            <li class="nav-item ">
     {% if request.user.id|stringformat:"s" in request.session.keys %}
                <a href="{% url 'cart:cart_detail' %}">
                <img src="{% static 'img/cart2.jpg' %}" width="30" height="30">
                    </a>
     {% else %}
                <img src="{% static 'img/cart1.jpg' %}" width="30" height="30">
     {% endif %}
            </li>
        </ul>

    </span>


      </div>
    </div>
  </nav>



    </div>
  </div>
</header>


<main>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel" >
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  {% block content %}

  {% endblock %}


</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
  </body>
</html>

shop/templates/shop/base_old.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>{% block mytitle%}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<div class="container" >
<header>
   <nav class="navbar navbar-expand-lg  navbar navbar-dark bg-dark container"  >
       <div class="container">
  <a class="navbar-brand" href="{% url 'shop:product_list' %}" class="logo">
    Bakery Total Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:product_list' %}">HOME</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">apple</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">banana</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">message board</a>
      </li>
    </ul>


<span style="vertical-align: middle; ">
    <form action="" class="form-inline my-2 my-lg-0" method="post" >
      {% csrf_token %}
        <div class="col-auto">

      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">search</div>
        </div>
        <input type="text" class="form-control" id="inlineFormInputGroup" name="searchword" placeholder="what can i">
           <span class="col-auto">
      <button type="submit" class="btn btn-primary mb-2">찾아보기</button>
    </span>
      </div>
    </div>

    </form></span>

  </div>


  <nav class="badge badge-secondary" style=" width:150px; line-height:200% "  >
 {% if user.is_authenticated %}
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
     {{ user.name }}
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="{% url 'cart:order_success'%}">주문내역</a></li>
    <li><a class="dropdown-item" href="{% url 'shop:profile_edit' %}">내정보수정</a></li>
    <li><a class="dropdown-item" href="{% url 'shop:logout_user' %}">로그아웃</a></li>
  </ul>
</div>
    {% else %}
    <font size="3" >누구세요?</font>
    <br>
    <a href="{% url 'shop:login_user' %}"><font size="3" >로그인</font></a>
      {% endif %}
    <div>
        {% if request.user.id|stringformat:"s" in request.session.keys %}
    <div class="cart">
    <a href="{% url 'cart:cart_detail'%}">Your Cart is not Empty</a>
    </div>
    {% else %}
    <div class="cart">
    Your Cart is Empty
    </div>
    {% endif %}
    </div>
    </nav>
           </div>
</nav>
</header>
<br>

{% block content %}{% endblock %}

<footer>
  <p class="text-light bg-dark container" align="center" >it is testing page for study : wavecanon@naver.com</p>
    </footer>
  </div>

</body>
</html>

shop/templates/shop/base_old2.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>{% block mytitle%}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body class="w-75 ">

<nav class="navbar navbar-dark bg-dark p-3 py-lg-4" >
<ul class="nav ">
    <li>
        <div class="container">
    <a class="navbar-brand" href="{% url 'shop:product_list' %}">
      <img src="{% static 'img/bee1.png' %}" alt="" width="50" height="50"> <!-- 이미지가 안나오면 확장자를 확인하고 바꿔보자 -->
    </a>
  </div>
    </li>

  <li class="nav-item " >
  <a class="nav-link" href="{% url 'shop:product_list' %}" style="color:#FFA500">홈으로</a>
  </li>
  <li class="nav-item " >
  <a class="nav-link" href="#" style="color:#FFA500">소개</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" style="color:#FFA500" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">캠핑</a>
    <ul class="dropdown-menu bg-dark" >
      <li><a class="dropdown-item" href="#" style="color:#FFA500">옷</a></li>
      <li><a class="dropdown-item" href="#" style="color:#FFA500">도구</a></li>
      <li><a class="dropdown-item" href="#" style="color:#FFA500">텐트/파라솔</a></li>
      <li><hr class="dropdown-divider" style="color:#FFA500"></li>
      <li><a class="dropdown-item" href="#" style="color:#FFA500">Separated link</a></li>
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#" style="color:#FFA500">운동</a>
  </li>
    <li class="nav-item">
    <a class="nav-link" href="#" style="color:#FFA500">음식</a>
  </li>
    <li class="nav-item">
    <a class="nav-link" href="#" style="color:#FFA500">문의게시판</a>
  </li>
    <li>
     <form class="d-flex">
         {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit" >Search</button>
    </form>
    </li>
</ul>

    <span>
        <ul>
       {% if user.is_authenticated %}
       <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" style="color:#FFA500" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
        {{ user.name }}</a>
    <ul class="dropdown-menu bg-dark" >
      <li><a class="dropdown-item" href="{% url 'shop:profile_edit' %}" style="color:#FFA500">정보수정</a></li>
      <li><a class="dropdown-item" href="{% url 'cart:order_success'%}" style="color:#FFA500">주문목록</a></li>
      <li><a class="dropdown-item" href="#" style="color:#FFA500">빈공란</a></li>
      <li><hr class="dropdown-divider" style="color:#FFA500"></li>
      <li><a class="dropdown-item" href="{% url 'shop:logout_user' %}" style="color:#FFA500">로그아웃</a></li>
    </ul>
    </li>
      {% else %}
            <li class="nav-item">
                <a href="{% url 'shop:login_user' %}" class="nav-link" style="color:#FFA500">로그인 하세요</a>
            </li>
            {% endif %}
            </ul>
        </span>
        <span class="p-2">
        <ul>
            <li class="nav-item ">
     {% if request.user.id|stringformat:"s" in request.session.keys %}
                <a href="{% url 'cart:cart_detail' %}">
                <img src="{% static 'img/cart2.jpg' %}" width="30" height="30">
                    </a>
     {% else %}
                <img src="{% static 'img/cart1.jpg' %}" width="30" height="30">
     {% endif %}
            </li>
        </ul>

    </span>
</nav>

{% block content %}{% endblock %}

<footer>
  <p class="text-light bg-dark container" align="center" >it is testing page for study : wavecanon@naver.com</p>
    </footer>
  </div>

</body>

</html>

shop/templates/shop/product_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
         {% static 'img/no_image.png' %}{% endif %}" width="250" height="250">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}"> {{ product.category }}</a></h2>
    <p class="price">{{ product.price }}&nbsp(원)</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="카드 담기">
    </form>
    {{ product.description|linebreaks }} <!--줄 바꿈을 <br>로, 이중 줄 바꿈을 <p>로 변형 -->
</div>
{% endblock %}